CRITICAL - 2022-11-29 02:31:13 --> You must use the "set" method to update an entry.
#0 C:\xampp\htdocs\ci4-sistemkasir\system\Database\BaseBuilder.php(1758): CodeIgniter\Database\BaseBuilder->validateInsert()
#1 C:\xampp\htdocs\ci4-sistemkasir\app\Models\ModelSatuan.php(15): CodeIgniter\Database\BaseBuilder->insert()
#2 C:\xampp\htdocs\ci4-sistemkasir\app\Controllers\Satuan.php(30): App\Models\ModelSatuan->InsertData(Array)
#3 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(832): App\Controllers\Satuan->InsertData()
#4 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Satuan))
#5 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4-sistemkasir\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-11-29 02:33:36 --> You must use the "set" method to update an entry.
#0 C:\xampp\htdocs\ci4-sistemkasir\system\Database\BaseBuilder.php(1758): CodeIgniter\Database\BaseBuilder->validateInsert()
#1 C:\xampp\htdocs\ci4-sistemkasir\app\Models\ModelSatuan.php(15): CodeIgniter\Database\BaseBuilder->insert()
#2 C:\xampp\htdocs\ci4-sistemkasir\app\Controllers\Satuan.php(30): App\Models\ModelSatuan->InsertData(Array)
#3 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(832): App\Controllers\Satuan->InsertData()
#4 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Satuan))
#5 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4-sistemkasir\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2022-11-29 02:41:13 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-11-29 02:41:13 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\ci4-sistemkasir\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4-sistemkasir\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\ci4-sistemkasir\app\Models\ModelSatuan.php(11): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\ci4-sistemkasir\app\Controllers\Satuan.php(22): App\Models\ModelSatuan->AllData()
#4 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(832): App\Controllers\Satuan->index()
#5 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Satuan))
#6 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4-sistemkasir\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-11-29 02:41:14 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\ci4-sistemkasir\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\ci4-sistemkasir\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\Satuan), true)
#2 C:\xampp\htdocs\ci4-sistemkasir\system\Debug\Exceptions.php(234): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4-sistemkasir\system\Debug\Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\ci4-sistemkasir\system\Debug\Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-11-29 02:41:16 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-11-29 02:41:16 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\ci4-sistemkasir\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4-sistemkasir\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\ci4-sistemkasir\app\Models\ModelSatuan.php(11): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\ci4-sistemkasir\app\Controllers\Satuan.php(22): App\Models\ModelSatuan->AllData()
#4 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(832): App\Controllers\Satuan->index()
#5 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Satuan))
#6 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4-sistemkasir\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-11-29 02:41:17 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\ci4-sistemkasir\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\ci4-sistemkasir\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\Satuan), true)
#2 C:\xampp\htdocs\ci4-sistemkasir\system\Debug\Exceptions.php(234): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4-sistemkasir\system\Debug\Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\ci4-sistemkasir\system\Debug\Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-11-29 02:41:42 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-11-29 02:41:42 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\ci4-sistemkasir\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4-sistemkasir\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\ci4-sistemkasir\app\Models\ModelSatuan.php(11): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\ci4-sistemkasir\app\Controllers\Satuan.php(22): App\Models\ModelSatuan->AllData()
#4 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(832): App\Controllers\Satuan->index()
#5 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Satuan))
#6 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4-sistemkasir\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-11-29 02:41:42 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\ci4-sistemkasir\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\ci4-sistemkasir\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\Satuan), true)
#2 C:\xampp\htdocs\ci4-sistemkasir\system\Debug\Exceptions.php(234): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4-sistemkasir\system\Debug\Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\ci4-sistemkasir\system\Debug\Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-11-29 02:42:27 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-11-29 02:42:27 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\ci4-sistemkasir\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4-sistemkasir\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\ci4-sistemkasir\app\Models\ModelSatuan.php(11): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\ci4-sistemkasir\app\Controllers\Satuan.php(22): App\Models\ModelSatuan->AllData()
#4 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(832): App\Controllers\Satuan->index()
#5 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Satuan))
#6 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4-sistemkasir\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-11-29 02:42:27 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\ci4-sistemkasir\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\ci4-sistemkasir\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\Satuan), true)
#2 C:\xampp\htdocs\ci4-sistemkasir\system\Debug\Exceptions.php(234): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4-sistemkasir\system\Debug\Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\ci4-sistemkasir\system\Debug\Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-11-29 02:43:32 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-11-29 02:43:32 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\ci4-sistemkasir\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4-sistemkasir\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\ci4-sistemkasir\app\Models\ModelSatuan.php(11): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\ci4-sistemkasir\app\Controllers\Satuan.php(22): App\Models\ModelSatuan->AllData()
#4 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(832): App\Controllers\Satuan->index()
#5 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Satuan))
#6 C:\xampp\htdocs\ci4-sistemkasir\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4-sistemkasir\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-11-29 02:43:32 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\ci4-sistemkasir\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\ci4-sistemkasir\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\Satuan), true)
#2 C:\xampp\htdocs\ci4-sistemkasir\system\Debug\Exceptions.php(234): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\ci4-sistemkasir\system\Debug\Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\ci4-sistemkasir\system\Debug\Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
